# Generated by Django 5.0.3 on 2024-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate_databases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('İsim', models.CharField(max_length=100)),
                ('Yapımcı', models.CharField(max_length=100)),
                ('Hakkında', models.TextField()),
                ('Tür', models.TextField()),
                ('Çıkış Tarihi', models.DateTimeField()),
                ('Arkaplan', models.CharField(max_length=500)),
                ('Poster', models.CharField(max_length=500)),
                ('Trailer', models.CharField(max_length=500)),
                ('savedate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
