# Generated by Django 5.0.3 on 2024-05-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_Genres_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Tür İsmi')),
                ('gen_id', models.CharField(max_length=2, verbose_name='Tür Kısaltma')),
                ('savedate', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Movies_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('production', models.CharField(max_length=100, verbose_name='Yapımcı')),
                ('about', models.TextField(verbose_name='Hakkında')),
                ('release', models.DateTimeField(verbose_name='Çıkış Tarihi')),
                ('imdb', models.IntegerField(verbose_name='IMDB')),
                ('metascritic', models.IntegerField(verbose_name='Metacritic')),
                ('background', models.CharField(max_length=500, verbose_name='Arkaplan')),
                ('poster', models.CharField(max_length=500, verbose_name='Poster')),
                ('trailer', models.CharField(max_length=500, verbose_name='Trailer')),
                ('savedate', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('isPublished', models.BooleanField(default=True, verbose_name='Yayın Durumu')),
                ('genres', models.ManyToManyField(to='movies.movies_genres_table', verbose_name='Tür')),
            ],
        ),
    ]
