# Generated by Django 5.0.6 on 2024-05-19 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Film Kategori ID'),
        ),
        migrations.AlterField(
            model_name='movies_comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Film Yorum ID'),
        ),
        migrations.AlterField(
            model_name='movies_like',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Film Beğeni ID'),
        ),
        migrations.AlterField(
            model_name='movies_table',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Film ID'),
        ),
        migrations.AlterField(
            model_name='movies_table',
            name='imdb',
            field=models.FloatField(verbose_name='IMDB'),
        ),
        migrations.AlterField(
            model_name='movies_table',
            name='metacritic',
            field=models.FloatField(verbose_name='Metacritic'),
        ),
    ]
