# Generated by Django 5.0.6 on 2024-05-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_category_id_alter_movies_comment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies_table',
            old_name='url_name',
            new_name='urlname',
        ),
    ]
