# Generated by Django 4.1.13 on 2024-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Resmi'),
        ),
    ]
