# Generated by Django 5.0.6 on 2024-05-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Kitap Kategori ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tür İsmi')),
                ('catshort', models.CharField(max_length=3, verbose_name='Kitap Türü Kısaltması')),
                ('savedate', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kitap Kategori',
                'verbose_name_plural': 'Kitap Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Book_Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Kitap Yorum ID')),
                ('userID', models.CharField(max_length=100, verbose_name='Kullanıcı ID')),
                ('bookID', models.CharField(max_length=100, verbose_name='Kitap ID')),
                ('comment', models.TextField(max_length=2000, verbose_name='Yorum')),
                ('savedate', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kitap Yorum',
                'verbose_name_plural': 'Kitap Yorumları',
            },
        ),
        migrations.CreateModel(
            name='Book_Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Kitap Beğeni ID')),
                ('userID', models.CharField(max_length=100, verbose_name='Kullanıcı ID')),
                ('bookID', models.CharField(max_length=100, verbose_name='Kitap ID')),
                ('savedate', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kitap Beğeni',
                'verbose_name_plural': 'Kitap Beğenileri',
            },
        ),
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Kitap ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('soldlink', models.URLField(verbose_name='Satış Linki')),
                ('urlname', models.CharField(max_length=100, verbose_name='URL İsmi')),
                ('production', models.CharField(max_length=100, verbose_name='Yapımcı')),
                ('about', models.TextField(max_length=2000, verbose_name='Hakkında')),
                ('release', models.DateTimeField(verbose_name='Çıkış Tarihi')),
                ('background', models.URLField(verbose_name='Arkaplan URL')),
                ('poster', models.URLField(verbose_name='Poster URL')),
                ('savedate', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('isPublished', models.BooleanField(default=True, verbose_name='Yayın Durumu')),
                ('like', models.IntegerField(verbose_name='Beğeni Sayısı')),
                ('category', models.ManyToManyField(to='book.book_category', verbose_name='Tür')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
            },
        ),
    ]
