# Generated by Django 5.0.6 on 2024-05-19 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kitap Kategori ID'),
        ),
        migrations.AlterField(
            model_name='book_comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kitap Yorum ID'),
        ),
        migrations.AlterField(
            model_name='book_like',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kitap Beğeni ID'),
        ),
        migrations.AlterField(
            model_name='book_table',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kitap ID'),
        ),
    ]
