# Generated by Django 5.0.6 on 2024-05-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games_table',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Beğeni sayısı'),
        ),
    ]
