# Generated by Django 5.0.6 on 2024-05-19 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_games_table_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Oyun Kategori ID'),
        ),
        migrations.AlterField(
            model_name='game_comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Oyun Yorum ID'),
        ),
        migrations.AlterField(
            model_name='game_like',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Oyun Beğeni ID'),
        ),
        migrations.AlterField(
            model_name='games_table',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Oyun ID'),
        ),
        migrations.AlterField(
            model_name='games_table',
            name='imdb',
            field=models.FloatField(verbose_name='IMDB'),
        ),
        migrations.AlterField(
            model_name='games_table',
            name='metascritic',
            field=models.FloatField(verbose_name='Metacritic'),
        ),
    ]
